"""initial tables

Revision ID: 6048ae2a7bcb
Revises: 
Create Date: 2023-05-03 13:04:11.547997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6048ae2a7bcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'doctors_data',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('login', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'patients',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('birthdate', sa.DATE(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'patients_data',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('uploaded_by_doctor', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('data_type', sa.String(), nullable=True),
        sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('data_url', sa.String(), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by_doctor'], ['doctors_data.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'patients_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('condition_title', sa.String(), nullable=True),
        sa.Column('condition_details', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients_history')
    op.drop_table('patients_data')
    op.drop_table('patients')
    op.drop_table('doctors_data')
    # ### end Alembic commands ###
